name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  name: "CI Workflow"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: |
          echo Hello, ${{ env.name }}!
          echo "Repository Variable: ${{ vars.name1 }}"
          echo "Event Name: ${{ github.event_name }}"
          echo "Secret Value: ${{ secrets.name2 }}"

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
